### ISSUE TITLE
Expired sessions

### ISSUE THREAD

**Issue by alex-eri** [alexpantyukhin/aiohttp-session-mongo#7]
You check `$exists` of `expire`

https://github.com/alexpantyukhin/aiohttp-session-mongo/blob/8fcc29671cb3481f35e42700fc7a5ed8a94e6c1b/aiohttp_session_mongo/__init__.py#L38

but it always set by 

https://github.com/alexpantyukhin/aiohttp-session-mongo/blob/8fcc29671cb3481f35e42700fc7a5ed8a94e6c1b/aiohttp_session_mongo/__init__.py#L87

to `None` or time

**Comment by alexpantyukhin** [comment]
Yes, you are right, thanks!
